### ISSUE TITLE
CKContainer.default().accountStatus does not get callback

### ISSUE THREAD

**Issue by leoMehlig** [ggruen/CloudKitSyncMonitor#1]
Thanks for this nice library!

I've noticed that `CKContainer.default().accountStatus` does not get a callback in iOS 14.2, which results in always getting a "No Account" status.

Has anybody else gotten this error or is something wrong on my side?

**Comment by ggruen** [comment]
Hmm, I haven't seen that in any of the iOS or iPadOS 14.2 betas I've used - it's possible something changed in the release version; I'm installing it now on my test iPad.

One thing I _have_ seen is that devices (especially simluators) will prompt for the Apple account's password, and if you don't enter it, you'll get setup errors. Also, if you haven't set up an iCloud account on your device, you'll get "No Account" status.

Can you provide info about the device you're using (iPhone, iPad, simulator, etc) and version of iOS 14.2 (and whether it's iOS or iPadOS - I've seen subtle differences between them)?

Thanks!

**Comment by ggruen** [comment]
Just tested on iOS 14.2 using Xcode 12.2 RC on a simulated iPhone 11 signed into an iCloud account and it detects the account status correctly. So, hopefully something is wrong on your side. :)

**Comment by leoMehlig** [comment]
Also just check in the simulator and everything works fine. 

But on my iPhone X with iOS 14.2 the callback is never called. Super weird.

**Comment by leoMehlig** [comment]
A reboot has indeed fixed the problem.
