### ISSUE TITLE
Use without SwiftUI context

### ISSUE THREAD

**Issue by teawithfruit** [ggruen/CloudKitSyncMonitor#10]
Can you please make a short example of how to use this library without a SwiftUI context?
I'd like to implement it in a class, but at this moment I'am a bit confused about the best way.

**Comment by ggruen** [comment]
Sorry, I could have sworn I replied to this long ago...

The library was really designed to be used with SwiftUI, as you can use the OS's built-in notification systems (probably more effectively) if you're using imperative-style views and controllers.

But what you could do is look at the code in SyncMonitor to see what notifications it monitors, and how, and copy/paste relevant bits into your views. The concepts of subscribing to NSPersistentCloudKitContainers' notifications and translating them into useful bits of information (and possibly even some of the structures used to represent that information) should port easily into views and controllers.

Sorry I don't have a more directly useful answer.
