### ISSUE TITLE
Can I used the class from Objective-C code ?

### ISSUE THREAD

**Issue by Mmisiek** [ggruen/CloudKitSyncMonitor#2]

**Comment by ggruen** [comment]
Hi Mmisiek - I'm not sure. I've bridged from Swift to Objective-C before, but not the other way around. Try searching in your favorite search engine for "How to use Swift library in Objective-C" - if it's possible to access Swift from Objective-C, then you should be able to use CloudKitSyncMonitor. You might need to modify the library to do so (e.g. adding `@objc` before methods). If you do so, please submit a pull request so others can benefit!

**Comment by Mmisiek** [comment]
I will look into it.

**Comment by ggruen** [comment]
Did you manage to get CloudKitSyncMonitor working from Objective-C? If so, can you give us a code snippet? If not, I'll just close this issue.

**Comment by Mmisiek** [comment]
Honestly I gave up on Cloud Kit, the updates to cloud are very slow and unreliable. Your tool is a must.

**Comment by ggruen** [comment]
Thank you - good luck with whatever sync solution you came up with. :)
