### ISSUE TITLE
'LocalizationValue' is only available in Mac Catalyst 15 or newer

### ISSUE THREAD

**Issue by stoope** [ggruen/CloudKitSyncMonitor#22]
- xCode 15.3
- CloudKitSyncMonitor 1.3.1

When trying to compile the project for Mac Catalyst target I'm getting the following error

`'init(localized:table:bundle:locale:comment:)' is only available in Mac Catalyst 15 or newer`
`'LocalizationValue' is only available in Mac Catalyst 15 or newer`

I guess we need to change `@available(iOS 15.0, macCatalyst 14.0, OSX 12, tvOS 15.0, watchOS 8, *)` to `@available(iOS 15.0, macCatalyst **15.0**, OSX 12, tvOS 15.0, watchOS 8, *)` in the library?

<img width="1352" alt="Screenshot 2024-06-24 at 16 42 22" src="https://github.com/ggruen/CloudKitSyncMonitor/assets/17287557/c441e8ad-4186-4522-8815-97ed3d29d11f">

**Comment by ggruen** [comment]
Hmm, that's not good. Updated available for macCatalyst to 15.0 in release 1.3.2. I'll close this issue, but please re-open if there's another issue as I can't test it at the moment.
