### ISSUE TITLE
Working with SwiftData?

### ISSUE THREAD

**Issue by FPST-08** [ggruen/CloudKitSyncMonitor#27]
Before I try to implement this package into my project: Does it work for SwiftData too? When using SwiftData and its automatic syncing capability, I don't with CKContainers for example. Will the package still work as if I was using CoreData? Under the hood SwiftData is still CoreData.

**Comment by ggruen** [comment]
Hi @FPST-08 ,

This package is specifically designed to work with `NSPersistentCloudKitContainer` and merely translates notifications sent by it into states that can easily be displayed by `SwiftUI`. It doesn't (intentionally) interact with `CoreData` or `CKContainer` (although I do notice an `import CoreData` in `SyncMonitor` now that I look again).

I haven't used `SwiftData`, so I don't know about whether it's an option to use with `NSPersistentCloudKitContainer` or not. If so, it's possible `CloudKitSyncMonitor` will work with `NSPersistentCloudKitContainer`/`SwiftData`, but you'll probably be in uncharted territory.

For what it's worth, the code that listens to `NSPersistentCloudKitContainer` is set up in [SyncMonitor at line 427](https://github.com/ggruen/CloudKitSyncMonitor/blob/main/Sources/CloudKitSyncMonitor/SyncMonitor.swift#L427).

Grant

**Comment by FPST-08** [comment]
Hi @ggruen ,

I've tried your Package in combination with SwiftData and it works exactly like it is supposed to be. Thank you for your awesome package. It is exactly what I was looking for.
