### ISSUE TITLE
Incorrect setupStatus if SyncMonitor is not accessed early

### ISSUE THREAD

**Issue by Tunous** [ggruen/CloudKitSyncMonitor#32]
I have added a dedicated screen for displaying iCloud sync status in my application. This is the only place where I access code from this library. What I've noticed is that setup status is almost always incorrect. It occurred to me now that this is because `SyncMonitor` had no chance to receive proper notifications. Workaround was to add `_ = SyncMonitor.shared` line before CloudKit related code for observation to register correctly.

I suggest adding information about this to documentation or somehow change implementation of `SyncMonitor` to determine proper setup status if observation is started late.

**Comment by JPToroDev** [comment]
@ggruen I just encountered this issue myself. The latest commit in my pull request addresses it by adding a static method called configure() to initialize the shared instance of SyncMonitor early on command. It also addresses a bug where syncStateSummary would return .accountNotAvailable when iCloudAccountStatus is nil (not yet determined), aligning with how the .noNetwork state is assessed.

**Comment by ggruen** [comment]
Just released version 3.0.0 with @JPToroDev 's changes (thanks again!), which includes a note in the README to call startMonitoring() in the initial screen or delegate. I think this resolves this issue, so I'm closing it - feel free to reopen (or open a new issue) if needed.
