### ISSUE TITLE
Xcode 13 compatibility - Needs import CloudKit

### ISSUE THREAD

**Issue by neilt** [ggruen/CloudKitSyncMonitor#6]
I know, I know it has only been a day!

None the less, the file SyncMonitor.swift needs `import CloudKit` added.

**Comment by ggruen** [comment]
Lol, good (quick) catch!

Not sure when I’ll get to this (I’ve learned to wait more than a day before I try to compile my app against the new beta since things change rapidly) - please submit a pull request if you get a chance.

**Comment by ggruen** [comment]
Merged and released in v1.1.1 - Thanks!
